# ML-07 — Baseline Action Score and Top-20 Review

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/rafiaburdibaloch-ui/flyrank-rafia/blob/main/work/notebooks/w04_baseline_score.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. My rule and its reason codes

*Write the rule in plain words first. Then the reason codes it can output.*

In [33]:
import pandas as pd
import numpy as np

In [34]:
import duckdb

con = duckdb.connect()
print("DuckDB connected successfully")

DuckDB connected successfully

In [35]:
import os

path = "data/raw/content_refresh_anonymized.csv"

print("File exists:", os.path.exists(path))

File exists: False

In [36]:
import os

for root, dirs, files in os.walk("."):
    level = root.replace(".", "").count(os.sep)
    if level <= 3:
        print(root, files[:10])

. []
./.config ['config_sentinel', 'gce', '.last_opt_in_prompt.yaml', '.last_survey_prompt.yaml', 'hidden_gcloud_config_universe_descriptor_data_cache_configs.db', 'active_config', 'default_configs.db', '.last_update_check.json']
./.config/logs []
./.config/logs/2026.09.16 ['13.26.04.283691.log', '13.26.17.091876.log', '13.26.29.139725.log', '13.26.30.459687.log', '13.26.15.129583.log', '13.25.37.877256.log']
./.config/configurations ['config_default']
./flyrank-rafia ['01_first_look_and_discovery.ipynb', 'LICENSE', 'CLAUDE.md', 'SETUP.md', 'AGENTS.md', 'README.md', 'requirements.txt', 'DATA_USE.md', '.gitignore', 'GUIDE.md']
./flyrank-rafia/work ['README.md', 'capstone_report_template.md']
./flyrank-rafia/work/notebooks ['w01_research_question.ipynb', 'w03_data_contract.ipynb', 'w03_feature_leakage_check.ipynb', 'w04_signal_audit.ipynb', 'w07_action_playbook.ipynb', 'w06_validation_audit.ipynb', 'w05_model.ipynb', 'w02_ml_task_framing.ipynb', 'w04_baseline_score.ipynb', 'capstone.ipynb']
./flyrank-rafia/.github []
./flyrank-rafia/.github/workflows ['personalize.yml', 'smoke-test.yml', 'data-path-smoke.yml']
./flyrank-rafia/outputs ['refresh_queue_sample.csv', 'model_report.md']
./flyrank-rafia/outputs/charts ['action_mix.svg', 'top_feature_importance.svg', 'trend_distribution.svg', 'confidence_mix.svg', 'top_reason_codes.svg']
./flyrank-rafia/.git ['HEAD', 'config', 'index', 'packed-refs', 'description']
./flyrank-rafia/.git/logs ['HEAD']
./flyrank-rafia/.git/hooks ['push-to-checkout.sample', 'applypatch-msg.sample', 'update.sample', 'pre-commit.sample', 'pre-rebase.sample', 'pre-merge-commit.sample', 'pre-receive.sample', 'fsmonitor-watchman.sample', 'pre-applypatch.sample', 'post-update.sample']
./flyrank-rafia/.git/objects []
./flyrank-rafia/.git/branches []
./flyrank-rafia/.git/refs []
./flyrank-rafia/.git/info ['exclude']
./flyrank-rafia/notebooks ['01_first_look_and_discovery.ipynb', '03_working_with_the_full_release.ipynb', '02_your_first_readable_model.ipynb']
./flyrank-rafia/skills ['README.md']
./flyrank-rafia/skills/writing-data-contracts ['SKILL.md']
./flyrank-rafia/skills/directing-your-ai-assistant ['SKILL.md']
./flyrank-rafia/skills/writing-research-papers ['SKILL.md']
./flyrank-rafia/skills/writing-honest-claims ['SKILL.md']
./flyrank-rafia/skills/flyrank []
./flyrank-rafia/skills/building-baselines ['SKILL.md']
./flyrank-rafia/skills/hunting-leakage-and-validating ['SKILL.md']
./flyrank-rafia/skills/deploying-static-pages ['SKILL.md']
./flyrank-rafia/skills/training-honest-models ['SKILL.md']
./flyrank-rafia/skills/querying-big-datasets ['SKILL.md']
./flyrank-rafia/skills/framing-ml-problems ['SKILL.md']
./flyrank-rafia/skills/auditing-signals ['SKILL.md']
./flyrank-rafia/data []
./flyrank-rafia/data/raw ['content_refresh_anonymized.csv']
./flyrank-rafia/submission ['README.md', 'paper_url.txt']
./flyrank-rafia/scripts ['02_baseline_score.py', 'run_all.py', '05_build_pdf_report.py', '03_train_model.py', 'ml_utils.py', '04_evaluate_and_export.py', '01_prepare_features.py']
./flyrank-rafia/docs ['flyrank-seo-research-march-2026.pdf', 'data-dictionary.md', 'ml-intern-dataset-and-lane-guide.md', 'intern-free-tooling-guide.md', 'ml-core-foundation-framework.md']
./sample_data ['README.md', 'anscombe.json', 'mnist_test.csv', 'mnist_train_small.csv', 'california_housing_test.csv', 'california_housing_train.csv']

In [37]:
!git clone https://github.com/rafiaburdibaloch-ui/flyrank-rafia.git

fatal: destination path 'flyrank-rafia' already exists and is not an empty directory.

In [38]:
import os

for root, dirs, files in os.walk("flyrank-rafia"):
    level = root.replace("flyrank-rafia", "").count(os.sep)

    if level <= 3:
        print(root)
        for file in files[:15]:
            print("   ", file)

flyrank-rafia
    01_first_look_and_discovery.ipynb
    LICENSE
    CLAUDE.md
    SETUP.md
    AGENTS.md
    README.md
    requirements.txt
    DATA_USE.md
    .gitignore
    GUIDE.md
flyrank-rafia/work
    README.md
    capstone_report_template.md
flyrank-rafia/work/notebooks
    w01_research_question.ipynb
    w03_data_contract.ipynb
    w03_feature_leakage_check.ipynb
    w04_signal_audit.ipynb
    w07_action_playbook.ipynb
    w06_validation_audit.ipynb
    w05_model.ipynb
    w02_ml_task_framing.ipynb
    w04_baseline_score.ipynb
    capstone.ipynb
flyrank-rafia/.github
flyrank-rafia/.github/workflows
    personalize.yml
    smoke-test.yml
    data-path-smoke.yml
flyrank-rafia/outputs
    refresh_queue_sample.csv
    model_report.md
flyrank-rafia/outputs/charts
    action_mix.svg
    top_feature_importance.svg
    trend_distribution.svg
    confidence_mix.svg
    top_reason_codes.svg
flyrank-rafia/.git
    HEAD
    config
    index
    packed-refs
    description
flyrank-rafia/.git/logs
    HEAD
flyrank-rafia/.git/logs/refs
flyrank-rafia/.git/hooks
    push-to-checkout.sample
    applypatch-msg.sample
    update.sample
    pre-commit.sample
    pre-rebase.sample
    pre-merge-commit.sample
    pre-receive.sample
    fsmonitor-watchman.sample
    pre-applypatch.sample
    post-update.sample
    pre-push.sample
    prepare-commit-msg.sample
    sendemail-validate.sample
    commit-msg.sample
flyrank-rafia/.git/objects
flyrank-rafia/.git/objects/pack
    pack-f154bc6458cbfdc5319127c0b98a10faf4322e6e.rev
    pack-f154bc6458cbfdc5319127c0b98a10faf4322e6e.pack
    pack-f154bc6458cbfdc5319127c0b98a10faf4322e6e.idx
flyrank-rafia/.git/objects/info
flyrank-rafia/.git/branches
flyrank-rafia/.git/refs
flyrank-rafia/.git/refs/tags
flyrank-rafia/.git/refs/heads
    main
flyrank-rafia/.git/refs/remotes
flyrank-rafia/.git/info
    exclude
flyrank-rafia/notebooks
    01_first_look_and_discovery.ipynb
    03_working_with_the_full_release.ipynb
    02_your_first_readable_model.ipynb
flyrank-rafia/skills
    README.md
flyrank-rafia/skills/writing-data-contracts
    SKILL.md
flyrank-rafia/skills/directing-your-ai-assistant
    SKILL.md
flyrank-rafia/skills/writing-research-papers
    SKILL.md
flyrank-rafia/skills/writing-honest-claims
    SKILL.md
flyrank-rafia/skills/flyrank
flyrank-rafia/skills/flyrank/flyrank-data
    SKILL.md
flyrank-rafia/skills/flyrank/flyrank-context
    SKILL.md
flyrank-rafia/skills/building-baselines
    SKILL.md
flyrank-rafia/skills/hunting-leakage-and-validating
    SKILL.md
flyrank-rafia/skills/deploying-static-pages
    SKILL.md
flyrank-rafia/skills/training-honest-models
    SKILL.md
flyrank-rafia/skills/querying-big-datasets
    SKILL.md
flyrank-rafia/skills/framing-ml-problems
    SKILL.md
flyrank-rafia/skills/auditing-signals
    SKILL.md
flyrank-rafia/data
flyrank-rafia/data/raw
    content_refresh_anonymized.csv
flyrank-rafia/submission
    README.md
    paper_url.txt
flyrank-rafia/scripts
    02_baseline_score.py
    run_all.py
    05_build_pdf_report.py
    03_train_model.py
    ml_utils.py
    04_evaluate_and_export.py
    01_prepare_features.py
flyrank-rafia/docs
    flyrank-seo-research-march-2026.pdf
    data-dictionary.md
    ml-intern-dataset-and-lane-guide.md
    intern-free-tooling-guide.md
    ml-core-foundation-framework.md

In [39]:
from pathlib import Path

print(Path("flyrank-rafia/skills/flyrank/flyrank-data/SKILL.md").read_text())

---
name: flyrank-data
description: The FlyRank internship datasets — the 30k-row starter CSV and its gotchas, the ~79M-row warehouse release tables and grains, panel warnings, access, and iteration rules. Load for EVERY task that touches the data. (Project-specific: delete this folder when reusing the skill library elsewhere.)
---

# FlyRank internship data

Two datasets. The small one ships in this repo; the big one is hosted and gated.

## 1. Starter dataset (in this repo)

`data/raw/content_refresh_anonymized.csv` — 30,000 rows × 44 columns, one row per pseudonymized
content item, 32 clients, trailing-90-day metrics. Full column reference: `docs/data-dictionary.md`
(keep it open). The gotchas that cause 90% of mistakes:

- **Rate columns are ×100 percentages**: `ctr = 0.76` means 0.76%, not 76%. Applies to ctr,
  engagement_rate, scroll_rate, ai_traffic_pct, trend_pct.
- **`avg_position = 0` means "no data"**, not rank zero (1,205 rows).
- **`scroll_rate` and `ai_traffic_pct` can exceed 100** — numerator and denominator come from
  different measurement systems. Not a bug; read the dictionary.
- **The label trap:** `is_declining_label` is derived from `trend_direction`, which is computed
  from `trend_pct`. Therefore `trend_direction` and `trend_pct` are NEVER features.
- **Missingness follows content_type** (one type has ~100% missing keyword data; another ~28%
  missing word_count) — a blind fillna(0) injects a category signal. Add has_-flags instead.
- **IDs (`content_id`, `client_id`) are pseudonyms:** grouping/joining/splitting only, never
  features. Use client_id for grouped train/test splits.

## 2. Warehouse release (Hugging Face, gated — instant approval)

`hf://datasets/FlyRank/internship-warehouse` — build v20260703:

| Table | Rows | Grain |
|---|---|---|
| `dim_clients` | 104 | one per pseudonymized client |
| `dim_content` | 519,606 | one per content item |
| `fact_content_daily_performance` | 78,835,655 | report_date × client × content (partitioned by month) |
| `fact_content_daily_performance_sample` | ~11.7M | same grain — the FINAL MONTH (June 2026) only; fine for query mechanics, NEVER for label logic |
| `fact_content_query_90d` | 2,414,248 | client × content × query hash, fixed 90-day window |

Dates: 2025-01-27 → 2026-06-30 (~17 months). Position column is `gsc_avg_position`.

**Panel warnings (they are real):**
- History depth differs wildly per client — check `dim_clients.gsc_data_start` before defining
  any time window; prefer per-client windows over one global calendar window.
- Rows before a client's `ga4_data_start` have GA4 columns zero-FILLED with
  `ga4_data_available = FALSE` — filter on the flag; zeros there are not "no engagement".
- A third of clients have little or no usable search/analytics history — expect to filter.
- The query table's per-content context columns repeat on every row: `ANY_VALUE()` them, never
  `SUM()`. Its 90-day window overlaps the snapshot's final months — if your label lives in the
  last 30 days, only `*_prev30`-style columns are safe features (window alignment first!).

**Access + iteration rules:** request gate access once (instant), READ token via Colab
Secrets (`HF_TOKEN`) or env var — never pasted in a cell (public repo!). Iterate on a
**mid-panel month partition** (e.g. `month=2026-03`), not the `_sample`: the `_sample` is the
panel's LAST month, i.e. the natural outcome window of any past→future label — develop label
logic there and you are developing inside your own test window. Treat the final month as a
sealed test month. Run the full 79M scan ONCE when the query is final and cache the result to
`work/outputs/`. Repeated full scans hit HTTP 429 rate limits.

## How to verify

- Start any session with `COUNT(*)` + `MIN/MAX(report_date)` on your table and match the
  numbers above.
- Grain-probe before aggregating: `GROUP BY <grain cols> HAVING COUNT(*) > 1 LIMIT 5` → empty.
- If a number looks absurd (a 400% rate, a giant ratio from 12 rows), re-read the gotchas
  before celebrating.

In [40]:
id="v9k3zq"
import pandas as pd

file_path = "flyrank-rafia/data/raw/content_refresh_anonymized.csv"

df = pd.read_csv(file_path)

print(df.shape)

(30000, 44)

In [41]:
print(df.columns.tolist())

['content_id', 'client_id', 'search_volume', 'competition', 'competition_level', 'cpc', 'content_type', 'main_intent', 'word_count', 'char_count', 'provider_used', 'model_used', 'impressions_90d', 'clicks_90d', 'pageviews_90d', 'sessions_90d', 'users_90d', 'engaged_sessions_90d', 'ai_sessions_90d', 'scroll_events_90d', 'days_with_impressions', 'days_with_sessions', 'impressions_last_30d', 'clicks_last_30d', 'sessions_last_30d', 'impressions_prev_30d', 'clicks_prev_30d', 'sessions_prev_30d', 'content_age_days', 'age_tier', 'age_tier_order', 'days_since_last_update', 'freshness_tier', 'word_count_tier', 'char_count_tier', 'ctr', 'avg_position', 'engagement_rate', 'scroll_rate', 'ai_traffic_pct', 'impression_tier', 'position_tier', 'trend_direction', 'trend_pct']

In [42]:
age_check = (
    df.groupby("age_tier")
    .agg(
        n=("content_id", "count"),
        avg_age_days=("content_age_days", "mean")
    )
    .reset_index()
)

age_check

  age_tier      n  avg_age_days
0  181-365  11368    281.140482
1    31-90    492     90.000000
2     365+   6360    462.690566
3   91-180  11780    127.507385

In [43]:
[c for c in df.columns if "refresh" in c.lower() or "flag" in c.lower()]

[]

In [44]:
from pathlib import Path

dictionary = Path("flyrank-rafia/docs/data-dictionary.md").read_text()

print(dictionary[:5000])

# Data Dictionary — `content_refresh_anonymized.csv`

One row per content item (page): **30,000 rows × 44 columns**, covering **32 pseudonymized
clients**. All metrics are aggregated over a trailing 90-day window ending at export time.
Keep this file open while you work.

## Read this first — the three rules that prevent 90% of mistakes

1. **Rate columns are ×100 percentages.** `ctr = 0.76` means **0.76%**, not 76%. Applies to
   `ctr`, `engagement_rate`, `scroll_rate`, `ai_traffic_pct`, `trend_pct`.
2. **The label comes from `trend_direction`.** The pipeline defines
   `is_declining_label = (trend_direction == "down")`, so `trend_direction` and `trend_pct`
   must **never** be model features — that's the leakage notebook 02 demonstrates.
3. **IDs are for grouping only.** `content_id` / `client_id` are pseudonyms: use them for
   joins and grouped train/test splits, never as features.

## Identifiers

| Column | Type | Meaning | Notes |
|---|---|---|---|
| `content_id` | text | Pseudonymous page id (`content_` + 12 hex chars) | Unique per row. Grouping/joins only |
| `client_id` | text | Pseudonymous client id (`client_` + 10 hex chars) | 32 distinct values. Use for **client-holdout splits** |

> **Missingness is systematic, not random.** Keyword-context columns are missing along
> `content_type` lines (e.g. `feedly article` rows have no keyword data at all). A blind
> `fillna(0)` therefore encodes content type into your features silently — check missingness
> per content_type before imputing.

## Keyword context (from content metadata)

| Column | Type | Meaning | Notes |
|---|---|---|---|
| `search_volume` | number | Search-volume estimate for the page's target keyword | 0–74,000 in this slice; blank for 2,468 rows with no keyword data |
| `competition` | number | Keyword competition score, 0–1 | Blank when no keyword data |
| `competition_level` | category | `LOW` / `MEDIUM` / `HIGH` | Blank when no keyword data |
| `cpc` | number | Cost-per-click estimate for the target keyword | Blank when no keyword data |
| `content_type` | category | `keyword article` / `feedly article` / `comparison article` | |
| `main_intent` | category | `informational` / `transactional` / `commercial` / `navigational` | Blank when unknown |

## Content properties

| Column | Type | Meaning | Notes |
|---|---|---|---|
| `word_count` | number | Article word count | Blank for 7,699 rows (not measured) |
| `char_count` | number | Article character count | Blank alongside `word_count` |
| `provider_used` | category | LLM provider that generated the article: `openai` / `google` / `other` | Blank when unknown. Not a model feature |
| `model_used` | category | LLM model name (e.g. `gemini-2.5-flash`, `gpt-4o-mini`) | Blank/`unknown` when not recorded. Not a model feature |
| `content_age_days` | number | Days since the content was created | Every row in this slice is ≥ 90 |
| `days_since_last_update` | number | Days since the content was last updated | |

## 90-day activity totals (GSC = Google Search Console, GA4 = Google Analytics)

| Column | Type | Meaning |
|---|---|---|
| `impressions_90d` | number | GSC search impressions (every row in this slice has ≥ 1) |
| `clicks_90d` | number | GSC clicks from search results |
| `pageviews_90d` | number | GA4 pageviews |
| `sessions_90d` | number | GA4 sessions |
| `users_90d` | number | GA4 users |
| `engaged_sessions_90d` | number | GA4 engaged sessions |
| `ai_sessions_90d` | number | GA4 sessions referred from AI tools — **click-throughs from AI assistants, not citations or rankings** |
| `scroll_events_90d` | number | GA4 scroll events |
| `days_with_impressions` | number | Days in the 90-day window with ≥ 1 impression (0–90) |
| `days_with_sessions` | number | Days in the window with ≥ 1 session (0–90) |

## 30-day comparison windows (the trend inputs)

| Column | Type | Meaning |
|---|---|---|
| `impressions_last_30d` | number | Impressions in the most recent 30 days |
| `clicks_last_30d` | number | Clicks, most recent 30 days |
| `sessions_last_30d` | number | Sessions, most recent 30 days |
| `impressions_prev_30d` | number | Impressions in the 30 days before that (days 31–60 back) |
| `clicks_prev_30d` | number | Clicks, days 31–60 back |
| `sessions_prev_30d` | number | Sessions, days 31–60 back |

## Derived rates (all ×100 percentages)

| Column | Formula | Notes |
|---|---|---|
| `ctr` | `clicks_90d / impressions_90d × 100` | 2 decimals. `0.76` = 0.76% |
| `avg_position` | mean GSC position over the window | 1 decimal. Lower is better. **`0` means "no position data", not position zero** (1,205 rows) |
| `engagement_rate` | `engaged_sessions_90d / sessions_90d × 100` | 0–100 |
| `scroll_rate` | `scroll_events_90d / pageviews_90d × 100` | **Can exceed 100** (multiple scroll events per pageview); blank when `pageviews_90d = 0` |
| `ai_traffic_pct` | `ai_sessions_90d / sessions_90d × 100` | **Can exceed 100** (AI-referred sessions are measured independently of total GA4 sessions)

In [45]:
from pathlib import Path

print(Path("flyrank-rafia").exists())

from pathlib import Path

skill = Path("flyrank-rafia/skills/building-baselines/SKILL.md").read_text()

print(skill)

True
---
name: building-baselines
description: Builds the transparent rule-based baseline every model must beat — a hand-written score with reason codes, ranked output, and precision@K evaluation. Use before training any model, or when someone reports model results with nothing to compare against.
---

# Building baselines

A model without a baseline is a number without a meaning. The baseline is a rule a human can
read — and its job is to be honestly beatable.

## Build it in this order

**1. Say the rule in plain words first.** "A page is worth reviewing if it used to get traffic,
it's getting old, and its position is slipping." If you can't say it, you can't code it.

**2. Code it as a transparent score.** Multiply/add simple conditions; no fitted weights:

```python
stale   = (df["days_since_update"] >= 180).astype(int)
visible = (df["impressions"] >= 500).astype(int)
df["score"] = stale * visible * df["impressions"]     # readable on purpose
```

**3. Attach reason codes.** Every scored item carries WHY it scored ("stale_but_visible",
"position_slipping"). Reason codes are what make a ranked list trustworthy to a human.

**4. Rank and evaluate at K.** For "which ones first?" problems the honest metric is
**precision@K**: of the top K the rule flags, how many were actually right?

```python
def precision_at_k(scores, labels, k):
    import numpy as np
    order = np.argsort(-np.asarray(scores))
    return np.asarray(labels)[order[:k]].mean()
```

Always print the **base rate** next to it (labels.mean()): precision@50 of 0.60 means little
until you know whether random picking gives 0.55 or 0.10.

**5. Review the top of the list by hand.** The top 20 is where bad logic shows itself. For each:
the action, the reason code, a confidence note, and what would make it wrong.

## Also useful

- A dummy baseline (predict the majority class / mean) is the floor below the floor — one line
  with sklearn's DummyClassifier, and surprisingly clarifying.
- Keep the baseline frozen once the model work starts. Moving the goalposts mid-game convinces
  nobody, including you.

## How to verify

- The rule fits in three sentences a non-engineer understands.
- precision@K is computed on the SAME data slice and labels the model will use later.
- The top-20 hand review found at least one weak pick — if it found none, look harder.

In [46]:
import json
from pathlib import Path

nb = json.loads(
    Path("flyrank-rafia/work/notebooks/w04_signal_audit.ipynb").read_text()
)

for cell in nb["cells"]:
    text = "".join(cell.get("source", []))

    if any(word in text.lower() for word in ["refresh", "stale", "flag", "quick-win"]):
        print("=" * 60)
        print(text)

============================================================
# ML-06 — Signal Audit: Do the Flags Hold?

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/rafiaburdibaloch-ui/flyrank-rafia/blob/main/work/notebooks/w04_signal_audit.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.
============================================================
## 3. The flag-linked test

*Pick a signal one of FlyRank's real flags relies on. Does the data support the rule's assumption?*

In [47]:
for i, cell in enumerate(nb["cells"]):
    text = "".join(cell.get("source", []))

    if "The flag-linked test" in text:
        print("Section 3 starts at cell:", i)
        print("\n--- SECTION 3 AND NEXT CELLS ---\n")

        for j in range(i, min(i + 8, len(nb["cells"]))):
            print(f"\n### CELL {j} ###")
            print("".join(nb["cells"][j].get("source", [])))

Section 3 starts at cell: 5

--- SECTION 3 AND NEXT CELLS ---


### CELL 5 ###
## 3. The flag-linked test

*Pick a signal one of FlyRank's real flags relies on. Does the data support the rule's assumption?*

### CELL 6 ###
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.


### CELL 7 ###
## 4. What this means in practice

*Two or three sentences: what a content team should take from this.*

### CELL 8 ###
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.


### CELL 9 ###
## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.

In [48]:
df["days_since_last_update"].describe()

count    30000.000000
mean        46.098300
std         42.078709
min          1.000000
25%         20.000000
50%         20.000000
75%        104.000000
max        373.000000
Name: days_since_last_update, dtype: float64

Signal 1 — Freshness: OPPOSITE

Pages that have gone longer without an update did not show weaker performance in this dataset. The 181+ day group had the highest average CTR (3.69%) and best average position (11.33), although it was small (n=174). I will not use freshness alone as a reason to prioritize a page.

In [49]:
freshness_check = (
    df.assign(
        update_bucket=pd.cut(
            df["days_since_last_update"],
            bins=[0, 30, 90, 180, np.inf],
            labels=["0-30", "31-90", "91-180", "181+"]
        )
    )
    .groupby("update_bucket", observed=False)
    .agg(
        n=("content_id", "count"),
        avg_ctr=("ctr", "mean"),
        avg_position=("avg_position", "mean")
    )
    .reset_index()
)

freshness_check

  update_bucket      n   avg_ctr  avg_position
0          0-30  20480  0.609021     15.685166
1         31-90    175  0.117543     16.538286
2        91-180   9171  0.238367     17.901461
3          181+    174  3.693276     11.325862

Signal 2 — CTR vs position: CONFIRMED

CTR decreases as average search position gets worse. Pages in positions 1–3 had an average CTR of 2.71%, compared with 0.15% for pages at 51+. This supports using CTR relative to search position when identifying pages that may need attention.

In [50]:
df["avg_position"].describe()
position_ctr_check = (
    df.assign(
        position_bucket=pd.cut(
            df["avg_position"],
            bins=[0, 3, 10, 20, 50, np.inf],
            labels=["1-3", "4-10", "11-20", "21-50", "51+"]
        )
    )
    .groupby("position_bucket", observed=False)
    .agg(
        n=("content_id", "count"),
        avg_ctr=("ctr", "mean")
    )
    .reset_index()
)

position_ctr_check

  position_bucket      n   avg_ctr
0             1-3   1141  2.714303
1            4-10  11842  0.651045
2           11-20   7273  0.323443
3           21-50   7225  0.222345
4             51+   1314  0.150784

In [51]:
import os

for root, dirs, files in os.walk("flyrank-rafia"):
    for file in files:
        if file.endswith((".py", ".md", ".ipynb", ".csv")):
            path = os.path.join(root, file)
            try:
                text = open(path, encoding="utf-8").read().lower()
                if any(word in text for word in ["quick-win", "quick win", "refresh flag", "refresh_flag", "ctr-fix", "ctr fix"]):
                    print(path)
            except:
                pass

flyrank-rafia/notebooks/02_your_first_readable_model.ipynb
flyrank-rafia/skills/flyrank/flyrank-context/SKILL.md
flyrank-rafia/docs/ml-intern-dataset-and-lane-guide.md

In [52]:
from pathlib import Path

path = "flyrank-rafia/skills/flyrank/flyrank-context/SKILL.md"
text = Path(path).read_text(encoding="utf-8")

print(text)

---
name: flyrank-context
description: FlyRank-specific background — what the company does, the search problem, and the hand-written flags story that the ML internship work builds on. Load for context when an assignment references FlyRank's product, flags, or the "beat the rule" framing. (Project-specific: delete this folder when reusing the skill library elsewhere.)
---

# FlyRank context

**What FlyRank is.** FlyRank builds content as infrastructure: it researches, writes, publishes
content straight into a client's website, then watches search data and optimizes — the full
cycle, run by algorithms and AI rather than people doing it by hand.

**The problem this internship works on.** Content that gets found in Google search ranks, then
quietly decays: rankings slip, clicks drop, and most teams notice too late. The valuable
decision is: *out of thousands of pages, which one should a human fix FIRST?* That is a ranking
problem on messy, real search data — exactly where a learned model can beat a fixed rule.

**The flags story (why "beat the rule" is the framing).** FlyRank's product already flags pages
today — a health score, quick-win tags, needs-attention flags. These are hand-written rules:
if-this-then-that, thresholds chosen by hand. They work, and they run in production. But rules
run out where signals get many, tangled, and shifting — and no trained model has replaced them
yet. The intern capstone lives exactly in that gap.

**Two things this means for your work:**
1. **Product flags are outputs, never inputs.** health_score and friends encode a decision
   someone already made. Use them as a baseline to beat — never as model features (that's a
   circular result; see the leakage skill).
2. **Honest language is house culture.** FlyRank publishes findings as observed / measured /
   directional / decision-support — never "we predicted Google's algorithm." Your work follows
   the same claim discipline.

**The data provenance in one line.** Google Search Console + Google Analytics land in BigQuery,
sync daily, aggregate into warehouse tables, and ship to interns as a pseudonymized public-safe
release (details in the flyrank-data skill).

## How to verify you have the context

You can answer, in one sentence each: what FlyRank sells, what decision the capstone improves,
why product flags can't be features, and which four words describe allowed claim language.

In [53]:
from pathlib import Path

path = "flyrank-rafia/docs/ml-intern-dataset-and-lane-guide.md"
text = Path(path).read_text(encoding="utf-8")

for i, line in enumerate(text.splitlines(), 1):
    if any(word in line.lower() for word in ["quick-win", "quick win", "refresh", "ctr", "flag", "needs-attention"]):
        print(f"{i}: {line}")

12: > This starter repo ships only the small anonymized starter dataset (`data/raw/content_refresh_anonymized.csv`).
25: - its verified committed outputs (`outputs/model_report.md`, `outputs/refresh_queue_sample.csv`, `outputs/charts/`); `outputs/model_results.json` is regenerated when you run the pipeline;
26: - the small anonymized starter dataset (`data/raw/content_refresh_anonymized.csv`).
54: - Treat product scores and flags as useful background, not as the truth.
86: | Refresh / Content Opportunity Scoring | Core lane | starter playground plus warehouse support | Ranked review queue with scores, actions, and reason codes |
88: | CTR / Engagement Opportunity Scoring | Core lane | warehouse release or starter dataset | Ranked opportunity score; position/volume adjusted |
146: - The CTR and engagement lanes have enough direct signal, but you will still need minimum-volume filters (rules like "only look at pages with at least N impressions") to keep noise out.
178: | Observed signals | Real measurements from search, analytics, or content metadata | impressions, clicks, position, CTR, sessions, scroll rate, word count, age | Good candidate features, as long as they were known before the decision point |
180: | Product context | Rule-outputs FlyRank's app computes (`health_score`, `priority_score`, `action_type`, refresh flags) — these are NOT shipped in your data | `health_score`, `priority_score`, `action_type`, `refresh_tier`, flags | Not in your dataset. If you ever rebuild one yourself, treat it as background or as a baseline to beat — never as a feature or a label for discovery |
186: FlyRank's product computes rule-based decision flags and combined scores with hand-tuned SQL — things like `health_score`, `needs_ctr_fix`, `is_quick_win`, a `priority_score`, and an `action_type`. Those are how the live app decides which pages to surface.
188: Those product decisions are deliberately **not** in your data. Your data ships observable search and engagement signals, plus transparent derived buckets (tiers, `trend_direction`, `trend_pct`, ctr, rates) — and nothing else. This is on purpose, so you discover signal from evidence instead of accidentally copying the product's own answers.
192: The strongest labels for supervised learning come from **future observed outcomes**, not from a current decision. Prefer labels like: traffic that later declined, a page that later recovered, CTR that later changed, or engagement that later changed — always measured after a clearly defined decision point. If you ever choose to rebuild a product flag and predict it, say so out loud in your write-up, and present it honestly as "can I reproduce the existing rule?" rather than as a discovery.
201: data/raw/content_refresh_anonymized.csv
224: - Input: `data/raw/content_refresh_anonymized.csv`.
228: - The data ships observable signals only; FlyRank's product decision flags were never included, so there is nothing to strip out. The label is `trend_direction == "down"`.
232: - Numeric features: search volume, competition, CPC, word/char count, logged 90d impressions/clicks/sessions/AI sessions, days with impressions/sessions, age, freshness, CTR, average position, engagement rate, scroll rate, and AI traffic percentage.
238: baseline_refresh_score =
251: - `low_ctr_visible_page`: `impressions_90d >= 500`, `0 < avg_position <= 20`, and `ctr < 0.5`
257: final_refresh_score =
265: - `ctr_review_candidate`: `impressions_90d >= 500`, average position 1-20, and `ctr < 0.5`
307: To prove that a refresh CAUSED a recovery, you would need an experiment or another causal design — something this data alone cannot give you. Most capstones here are **decision-support** projects: they rank candidates so a human reviewer spends their limited time on the most promising pages first.
327: | SERP or AI click loss | Impressions and position hold steady while clicks drop (the search page itself changed) | Look at impressions, clicks, CTR, position, and AI-session context separately, not as one blob |
376: ### Lane 2: Refresh / Content Opportunity Scoring
381: Which pages should be reviewed first for refresh, expansion, protection, pruning, or monitoring?
402: - CTR or engagement review context.
414: - treating "declining" as a guarantee that a refresh will pay off;
464: ### Lane 4: CTR / Engagement Opportunity Scoring
481: - CTR;
490: - expected CTR by position tier (pages at position 1 always get more clicks than pages at position 9 — compare pages only to others in the same tier);
491: - residual or gap analysis — how far below its tier's expected CTR a page sits;
497: - a ranked list of CTR or engagement review candidates;
498: - reason codes such as high impressions, low CTR, strong position, enough volume, enough sessions, or weak engagement;
503: - comparing CTR across different positions without adjusting for position;
505: - assuming low CTR always means the title or meta description is bad.
572: - prior state after a refresh -> later recovery signal, if the data safely supports it.
599: - If you ever rebuild a product decision flag, `priority_score`, `action_type`, or `health_score`, do not use it as an ordinary model feature — your data is observable-only precisely to protect you from this.
601: - Do not claim a refresh caused a recovery unless you ran an explicit experiment or causal design.
612: - where CTR becomes weak for a position tier;
648: - If you rebuilt any product output (`health_score`, a decision flag, `priority_score`, or `action_type`), did it slip in as a normal feature?
667: - rebuilding a product decision flag and then feeding it to a discovery model as a feature;
668: - calling a product flag "the truth" without checking future outcomes;
702: - claims that a refresh caused a recovery, unless you ran a valid causal design.

Signal 2 — FlyRank low_ctr_visible_page flag: CONFIRMED

The documented FlyRank flag identifies pages with at least 500 impressions, position 1–20, and CTR below 0.5%. In this dataset, 9,759 pages meet the flag conditions and have an average CTR of 0.185%, compared with 0.668% for the 20,241 pages that do not. This supports using visible low-CTR pages as a review signal.

In [54]:
low_ctr_visible = (
    (df["impressions_90d"] >= 500)
    & (df["avg_position"] > 0)
    & (df["avg_position"] <= 20)
    & (df["ctr"] < 0.5)
)

flag_check = (
    df.assign(low_ctr_visible_page=low_ctr_visible)
    .groupby("low_ctr_visible_page")
    .agg(
        n=("content_id", "count"),
        avg_ctr=("ctr", "mean"),
        avg_position=("avg_position", "mean")
    )
    .reset_index()
)

flag_check

   low_ctr_visible_page      n   avg_ctr  avg_position
0                 False  20241  0.667691     19.649642
1                  True   9759  0.185190      9.482836

In [55]:
df[[
    "impressions_90d",
    "avg_position",
    "ctr"
]].describe()

       impressions_90d  avg_position           ctr
count     30000.000000   30000.00000  30000.000000
mean       5200.366300      16.34238      0.510733
std       16838.019547      15.21679      3.279162
min           1.000000       0.00000      0.000000
25%          81.000000       6.20000      0.000000
50%         731.000000      10.80000      0.070000
75%        3615.250000      22.30000      0.290000
max      517715.000000     245.00000    100.000000

## 2. Build the ranked queue (writes the CSV)

*Code the score, rank everything, write work/outputs/baseline_action_score.csv.*

In [56]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.
queue = df.copy()

queue["eligible"] = (
    (queue["impressions_90d"] >= 500)
    & (queue["avg_position"] > 0)
    & (queue["avg_position"] <= 20)
)

queue["score"] = 0.0
queue["reason_code"] = "not_eligible"
queue["action"] = "monitor"

eligible = queue["eligible"]

queue.loc[eligible, "score"] = (
    (0.5 - queue.loc[eligible, "ctr"]).clip(lower=0) * 2
    + (20 - queue.loc[eligible, "avg_position"]) / 20
)

queue.loc[
    eligible & (queue["ctr"] < 0.5),
    "reason_code"
] = "low_ctr_visible_page"

queue.loc[
    eligible & (queue["ctr"] < 0.5),
    "action"
] = "review_ctr"

queue = queue.sort_values(
    ["score", "impressions_90d"],
    ascending=[False, False]
).reset_index(drop=True)

queue[[
    "content_id",
    "score",
    "action",
    "reason_code",
    "impressions_90d",
    "avg_position",
    "ctr"
]].head(20)

,content_id,score,action,reason_code,impressions_90d,avg_position,ctr
0,content_d0351144852b,1.970,review_ctr,low_ctr_visible_page,884,0.6,0.0
1,content_7e97f31ba9bb,1.965,review_ctr,low_ctr_visible_page,603,0.7,0.0
2,content_c90bfc85694f,1.945,review_ctr,low_ctr_visible_page,3047,1.1,0.0
3,content_1e57b71527e4,1.940,review_ctr,low_ctr_visible_page,1213,1.2,0.0
4,content_4bb993e9270e,1.935,review_ctr,low_ctr_visible_page,1986,1.3,0.0
5,content_81e0dfd4c3cc,1.935,review_ctr,low_ctr_visible_page,720,1.3,0.0
6,content_eb3b2c3bbc34,1.935,review_ctr,low_ctr_visible_page,580,1.3,0.0
7,content_134631e65b9e,1.925,review_ctr,low_ctr_visible_page,4417,1.5,0.0
8,content_1d2233dc3323,1.925,review_ctr,low_ctr_visible_page,1463,1.5,0.0
9,content_97a08f7b106c,1.925,review_ctr,low_ctr_visible_page,1108,1.5,0.0
10,content_fb4884e34467,1.925,review_ctr,low_ctr_visible_page,580,1.5,0.0
11,content_7a6cb4857fe6,1.920,review_ctr,low_ctr_visible_page,789,1.6,0.0
12,content_6e6694b67eb6,1.915,review_ctr,low_ctr_visible_page,1969,1.7,0.0
13,content_35d0f98ef4dc,1.910,review_ctr,low_ctr_visible_page,2146,1.8,0.0
14,content_eb72d6efc172,1.910,review_ctr,low_ctr_visible_page,630,1.8,0.0
15,content_53d353c3db0f,1.905,review_ctr,low_ctr_visible_page,1518,1.9,0.0
16,content_c7b87d5dd8a0,1.905,review_ctr,low_ctr_visible_page,1418,1.9,0.0
17,content_8cbda3f608d0,1.905,review_ctr,low_ctr_visible_page,866,1.9,0.0
18,content_b5964a1a276f,1.900,review_ctr,low_ctr_visible_page,1872,2.0,0.0
19,content_0c8cb6bad4a7,1.900,review_ctr,low_ctr_visible_page,502,2.0,0.0

In [57]:
from pathlib import Path

output_dir = Path("flyrank-rafia/work/outputs")
output_dir.mkdir(parents=True, exist_ok=True)

output_path = output_dir / "baseline_action_score.csv"

queue[[
    "content_id",
    "score",
    "action",
    "reason_code",
    "impressions_90d",
    "avg_position",
    "ctr"
]].to_csv(output_path, index=False)

print(f"Saved: {output_path}")
print(f"Rows written: {len(queue)}")

Saved: flyrank-rafia/work/outputs/baseline_action_score.csv
Rows written: 30000

## 3. Top-20 review

*For each of the top 20: action, reason code, confidence note, and what would make it wrong.*

### Top-20 review

All top-20 pages are assigned **review_ctr** with reason code **low_ctr_visible_page** because they have at least 500 impressions, average position between 1 and 20, and CTR below 0.5%.

* **content_d0351144852b** — Review CTR; 884 impressions, position 0.6, CTR 0.0%. High confidence because it has strong visibility but no recorded clicks. It could be wrong if the CTR data is sparse or tracking is incomplete.
* **content_7e97f31ba9bb** — Review CTR; 603 impressions, position 0.7, CTR 0.0%. Strong position and sufficient volume support the review. It could be wrong if the measured clicks are incomplete.
* **content_c90bfc85694f** — Review CTR; 3,047 impressions, position 1.1, CTR 0.0%. Very strong visibility with no clicks. It could be wrong if tracking or attribution is unreliable.
* **content_1e57b71527e4** — Review CTR; 1,213 impressions, position 1.2, CTR 0.0%. Strong position and volume make this a clear review candidate. It could be wrong if the zero CTR is a measurement issue.
* **content_4bb993e9270e** — Review CTR; 1,986 impressions, position 1.3, CTR 0.0%. Good visibility with no recorded clicks. It could be wrong if click data is incomplete.
* **content_81e0dfd4c3cc** — Review CTR; 720 impressions, position 1.3, CTR 0.0%. Meets the volume and visibility conditions. It could be wrong if the observed CTR is unreliable.
* **content_eb3b2c3bbc34** — Review CTR; 580 impressions, position 1.3, CTR 0.0%. Sufficient impressions and strong position support review. It could be wrong if the sample is not representative.
* **content_134631e65b9e** — Review CTR; 4,417 impressions, position 1.5, CTR 0.0%. High visibility makes the zero CTR notable. It could be wrong if tracking is incomplete.
* **content_1d2233dc3323** — Review CTR; 1,463 impressions, position 1.5, CTR 0.0%. Strong position and sufficient volume support review. It could be wrong if clicks were under-recorded.
* **content_97a08f7b106c** — Review CTR; 1,108 impressions, position 1.5, CTR 0.0%. Good visibility with no recorded clicks. It could be wrong if the CTR measurement is incomplete.
* **content_fb4884e34467** — Review CTR; 580 impressions, position 1.5, CTR 0.0%. Meets the minimum-volume and position conditions. It could be wrong if the sample is too limited.
* **content_7a6cb4857fe6** — Review CTR; 789 impressions, position 1.6, CTR 0.0%. Strong position and enough impressions support review. It could be wrong if click tracking is incomplete.
* **content_6e6694b67eb6** — Review CTR; 1,969 impressions, position 1.7, CTR 0.0%. Good visibility with zero recorded CTR. It could be wrong if the observed data is incomplete.
* **content_35d0f98ef4dc** — Review CTR; 2,146 impressions, position 1.8, CTR 0.0%. Strong visibility makes this a useful review candidate. It could be wrong if clicks were not fully captured.
* **content_eb72d6efc172** — Review CTR; 630 impressions, position 1.8, CTR 0.0%. Meets the rule conditions clearly. It could be wrong if the CTR is affected by measurement issues.
* **content_53d353c3db0f** — Review CTR; 1,518 impressions, position 1.9, CTR 0.0%. Sufficient volume and strong position support review. It could be wrong if click data is incomplete.
* **content_c7b87d5dd8a0** — Review CTR; 1,418 impressions, position 1.9, CTR 0.0%. Strong search visibility with no recorded clicks. It could be wrong if CTR tracking is unreliable.
* **content_8cbda3f608d0** — Review CTR; 866 impressions, position 1.9, CTR 0.0%. Meets the volume and position conditions. It could be wrong if the observed zero CTR is not representative.
* **content_b5964a1a276f** — Review CTR; 1,872 impressions, position 2.0, CTR 0.0%. Good visibility and sufficient volume support review. It could be wrong if click measurement is incomplete.
* **content_0c8cb6bad4a7** — Review CTR; 502 impressions, position 2.0, CTR 0.0%. Just above the minimum volume threshold, so it is a weaker pick than higher-volume rows. It could be wrong if the smaller sample is unstable.

In [58]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.
top20 = queue.head(20)[[
    "content_id",
    "score",
    "action",
    "reason_code",
    "impressions_90d",
    "avg_position",
    "ctr"
]]

top20

,content_id,score,action,reason_code,impressions_90d,avg_position,ctr
0,content_d0351144852b,1.970,review_ctr,low_ctr_visible_page,884,0.6,0.0
1,content_7e97f31ba9bb,1.965,review_ctr,low_ctr_visible_page,603,0.7,0.0
2,content_c90bfc85694f,1.945,review_ctr,low_ctr_visible_page,3047,1.1,0.0
3,content_1e57b71527e4,1.940,review_ctr,low_ctr_visible_page,1213,1.2,0.0
4,content_4bb993e9270e,1.935,review_ctr,low_ctr_visible_page,1986,1.3,0.0
5,content_81e0dfd4c3cc,1.935,review_ctr,low_ctr_visible_page,720,1.3,0.0
6,content_eb3b2c3bbc34,1.935,review_ctr,low_ctr_visible_page,580,1.3,0.0
7,content_134631e65b9e,1.925,review_ctr,low_ctr_visible_page,4417,1.5,0.0
8,content_1d2233dc3323,1.925,review_ctr,low_ctr_visible_page,1463,1.5,0.0
9,content_97a08f7b106c,1.925,review_ctr,low_ctr_visible_page,1108,1.5,0.0
10,content_fb4884e34467,1.925,review_ctr,low_ctr_visible_page,580,1.5,0.0
11,content_7a6cb4857fe6,1.920,review_ctr,low_ctr_visible_page,789,1.6,0.0
12,content_6e6694b67eb6,1.915,review_ctr,low_ctr_visible_page,1969,1.7,0.0
13,content_35d0f98ef4dc,1.910,review_ctr,low_ctr_visible_page,2146,1.8,0.0
14,content_eb72d6efc172,1.910,review_ctr,low_ctr_visible_page,630,1.8,0.0
15,content_53d353c3db0f,1.905,review_ctr,low_ctr_visible_page,1518,1.9,0.0
16,content_c7b87d5dd8a0,1.905,review_ctr,low_ctr_visible_page,1418,1.9,0.0
17,content_8cbda3f608d0,1.905,review_ctr,low_ctr_visible_page,866,1.9,0.0
18,content_b5964a1a276f,1.900,review_ctr,low_ctr_visible_page,1872,2.0,0.0
19,content_0c8cb6bad4a7,1.900,review_ctr,low_ctr_visible_page,502,2.0,0.0

## 4. Weak picks + leakage check

*Which picks look wrong and why? Confirm no product flags or future windows leaked in.*

### Weak picks + leakage check

The weakest pick in the top 20 is **content_0c8cb6bad4a7** because it has only 502 impressions, just above the 500-impression threshold. Its position is still strong at 2.0 and its CTR is 0.0%, so it remains a reasonable review candidate, but the smaller volume makes the signal less stable.

The rule does not use product flags, `trend_direction`, or `trend_pct`. It uses only 90-day performance fields and current page-level metrics. No future-window or label-derived inputs are used.

In [59]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.
scoring_features = [
    "impressions_90d",
    "avg_position",
    "ctr"
]

forbidden_features = ["trend_direction", "trend_pct"]

print("Scoring features:")
print(scoring_features)

print("\nForbidden label-derived features used in scoring:")
used_forbidden = [col for col in forbidden_features if col in scoring_features]
print(used_forbidden)

print("\nProduct flag columns in dataset:")
print([
    col for col in df.columns
    if "flag" in col.lower() or "health_score" in col.lower()
])

assert len(used_forbidden) == 0

print("\nLeakage check passed.")

Scoring features:
['impressions_90d', 'avg_position', 'ctr']

Forbidden label-derived features used in scoring:
[]

Product flag columns in dataset:
[]

Leakage check passed.

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.